version: '3'
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    command: -storageDataPath=/victoria-metrics-data
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    ports:
      - 8428:8428

  grafana:
    image: grafana/grafana
    depends_on:
      - victoriametrics
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  victoria-metrics-data:
  grafana-storage:
